export const taxonomyV1 = {
  version: 'v1',
  axes: {
    domain: [
      'ai_safety',
      'healthcare_ai',
      'climate_tech',
      'developer_tools',
      'fintech',
      'education_tech',
      'biosecurity',
      'public_sector_ai',
      'other',
    ],
    problem: [
      'reliability',
      'compliance',
      'adoption',
      'security',
      'cost_efficiency',
      'evaluation',
      'governance',
      'deployment_risk',
      'other',
    ],
    method: [
      'benchmarking',
      'causal_inference',
      'agentic_workflow',
      'policy_analysis',
      'incident_analysis',
      'market_sizing',
      'systematic_review',
      'comparative_case_study',
      'other',
    ],
    evidence: [
      'papers',
      'production_incidents',
      'regulations',
      'market_data',
      'earnings_calls',
      'clinical_trials',
      'public_procurement',
      'benchmarks',
      'other',
    ],
    population: [
      'startups',
      'enterprise_teams',
      'hospitals',
      'public_sector',
      'research_labs',
      'smbs',
      'critical_infrastructure_operators',
      'educators',
      'other',
    ],
    geography: ['us', 'eu', 'india', 'latam', 'uk', 'global', 'other'],
    time_horizon: ['6_months', '12_months', '3_years', '5_years', 'other'],
    objective: [
      'gap_mapping',
      'decision_support',
      'investment_thesis',
      'policy_recommendation',
      'risk_register',
      'roadmap_design',
      'other',
    ],
  },
};

export const axisOrder = [
  'domain',
  'problem',
  'method',
  'evidence',
  'population',
  'geography',
  'time_horizon',
  'objective',
];
